/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        navy: {
          950: '#0a0f1a',
          900: '#111827',
          800: '#1e293b',
        },
        gold: {
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
        },
        surface: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
        primary: '#00507d',
        'primary-container': '#0369a1',
        'on-primary': '#ffffff',
        'on-primary-container': '#cbe4ff',
        'surface-canvas': '#F8FAFC',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-variant': '#dae2fd',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        background: '#faf8ff',
        'on-surface': '#131b2e',
        'on-surface-variant': '#40474f',
        'border-hairline': '#E2E8F0',
        outline: '#707881',
        'outline-variant': '#c0c7d1',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        secondary: '#006a63',
        'secondary-container': '#99efe5',
        'on-secondary': '#ffffff',
        'role-driver': '#7C3AED',
        'role-driver-container': '#EDE9FE',
        'role-passenger': '#2563EB',
        'role-passenger-container': '#DBEAFE',
        'role-admin': '#059669',
        'role-admin-container': '#D1FAE5',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
      },
      borderColor: {
        hairline: '#E2E8F0',
      },
      fontFamily: {
        'body-base': ['Inter', 'system-ui', 'sans-serif'],
        'body-sm': ['Inter', 'system-ui', 'sans-serif'],
        'display-lg': ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        'headline-md': ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        'title-lg': ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        'title-md': ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        'stat-lg': ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        'label-caps': ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-lg': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '22px', letterSpacing: '0', fontWeight: '600' }],
        'body-base': ['15px', { lineHeight: '22px', letterSpacing: '0', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', letterSpacing: '0', fontWeight: '400' }],
        'stat-lg': ['30px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '700' }],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        base: '16px',
        lg: '20px',
        xl: '24px',
        '2xl': '32px',
        gutter: '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
      },
    },
  },
  plugins: [],
};